backend_assignuserhascourse_index:
    path:  /
    defaults:
        _controller: BackendBundle:AssignUserHasCourse:index
    requirements:
    methods: [GET]

backend_assignuserhascourse_assign:
    path:  /assign
    defaults:
        _controller: BackendBundle:AssignUserHasCourse:assign
    requirements:
    methods: [POST]

backend_assignuserhascourse_boxleft_has_boxright:
    path:  /boxleft-has-boxright
    defaults:
        _controller: BackendBundle:AssignUserHasCourse:boxleftHasBoxright
    requirements:
    methods: [POST]

backend_assignuserhascourse_boxleft_search:
    path: /box-left-search
    defaults: { _controller: BackendBundle:AssignUserHasCourse:boxLeftSearch }
    requirements:
    methods: [POST]

backend_assignuserhascourse_boxright_search:
    path: /box-right-search
    defaults: { _controller: BackendBundle:AssignUserHasCourse:boxRightSearch }
    requirements:
    methods: [POST]

backend_assignuserhascourse_info:
    path: /info
    defaults: { _controller: BackendBundle:AssignUserHasCourse:info }
    requirements:
    methods: [POST]

