backend_assignpointofsalehasproduct_index:
    path:  /
    defaults:
        _controller: BackendBundle:AssignPointOfSaleHasProduct:index
    requirements:
    methods: [GET]

backend_assignpointofsalehasproduct_assign:
    path:  /assign
    defaults:
        _controller: BackendBundle:AssignPointOfSaleHasProduct:assign
    requirements:
    methods: [POST]

backend_assignpointofsalehasproduct_boxleft_has_boxright:
    path:  /boxleft-has-boxright
    defaults:
        _controller: BackendBundle:AssignPointOfSaleHasProduct:boxleftHasBoxright
    requirements:
    methods: [POST]

backend_assignpointofsalehasproduct_boxleft_search:
    path: /box-left-search
    defaults: { _controller: BackendBundle:AssignPointOfSaleHasProduct:boxLeftSearch }
    requirements:
    methods: [POST]

backend_assignpointofsalehasproduct_boxright_search:
    path: /box-right-search
    defaults: { _controller: BackendBundle:AssignPointOfSaleHasProduct:boxRightSearch }
    requirements:
    methods: [POST]

backend_assignpointofsalehasproduct_info:
    path: /info
    defaults: { _controller: BackendBundle:AssignPointOfSaleHasProduct:info }
    requirements:
    methods: [POST]

backend_assignpointofsalehasproduct_associative_edit:
    path: /associative-edit
    defaults: { _controller: BackendBundle:AssignPointOfSaleHasProduct:associativeEdit }
    requirements:
    methods: [POST]

