backend_pointofsaletree_index:
    path:  /
    defaults:
        _controller: BackendBundle:PointOfSaleTree:index
    methods: [GET]

backend_pointofsaletree_create:
    path:  /create
    defaults:
        _controller: BackendBundle:PointOfSaleTree:create
    methods: [POST]

backend_pointofsaletree_createchild:
    path: /create-child
    defaults: { _controller: BackendBundle:PointOfSaleTree:createchild }
    requirements:
    methods: [POST]

backend_pointofsaletree_edit:
    path:  /edit
    defaults:
        _controller: BackendBundle:PointOfSaleTree:edit
    requirements:
    methods: [POST, PUT]

backend_pointofsaletree_delete:
    path:  /delete
    defaults:
        _controller: BackendBundle:PointOfSaleTree:delete
    requirements:
    methods: [POST, DELETE]

backend_pointofsaletree_view:
    path:  /view
    defaults:
        _controller: BackendBundle:PointOfSaleTree:view
    requirements:
    methods: [POST]
