backend_registerattendancestudent_listado_cursos:
    path:  /listado-cursos
    defaults:
        _controller: BackendBundle:RegisterAttendanceStudent:listadoCursos
    requirements:
    methods: [GET]

backend_registerattendancestudent_listado_alumnos:
    path:  /listado-alumnos/{curso_id}
    defaults:
        _controller: BackendBundle:RegisterAttendanceStudent:listadoAlumnos
        curso_id: null
    requirements:
    methods: [GET, POST]

