backend_setuptemplate_index:
    path:  /
    defaults:
        _controller: BackendBundle:TemplateSetup:index
    methods: [GET]

backend_setuptemplate_assign:
    path:  /assign
    defaults:
        _controller: BackendBundle:TemplateSetup:assign
    methods: [PUT]

backend_setuptemplate_manage:
    path:  /manage/{template_id}
    defaults:
        _controller: BackendBundle:TemplateSetup:manage
    methods: [GET]

backend_setuptemplate_info:
    path:  /info
    defaults:
        _controller: BackendBundle:TemplateSetup:info
    requirements:
    methods: [POST]