backend_setupedittemplate_index:
    path: /{template_id}
    defaults:
        _controller: BackendBundle:TemplateSetupEdit:index
    methods: [GET]

backend_setupedittemplate_module:
    path: /module/{template_has_module_id}
    defaults:
        _controller: BackendBundle:TemplateSetupEdit:module
        template_has_module_id: null
    methods: [GET]

backend_setupedittemplate_info:
    path: /info
    defaults:
        _controller: BackendBundle:TemplateSetupEdit:info
    requirements:
    methods: [POST]

backend_setupedittemplate_save:
    path: /module-save
    defaults:
        _controller: BackendBundle:TemplateSetupEdit:moduleSave
    methods: [POST]



#backend_product_index:
#    path: /
#    defaults: { _controller: 'BackendBundle:Product:index' }
#    methods: [GET]
backend_templatesetupedit_create:
    path: /create
    defaults: { _controller: BackendBundle:TemplateSetupEdit:create }
    methods: [POST]

backend_templatesetupedit_edit:
    path: /edit
    defaults: { _controller: BackendBundle:TemplateSetupEdit:edit }
    methods: [POST, PUT]

backend_templatesetupedit_delete:
    path: /delete
    defaults: { _controller: BackendBundle:TemplateSetupEdit:delete }
    methods: [POST, DELETE]

backend_templatesetupedit_view:
    path: /view
    defaults: { _controller: BackendBundle:TemplateSetupEdit:view }
    methods: [POST]

backend_templatesetupedit_info:
    path: /info
    defaults: { _controller: BackendBundle:TemplateSetupEdit:info }
    methods: [POST]
