backend_templatemodule_index:
    path:  /
    defaults:
        _controller: BackendBundle:TemplateModule:index
    methods: [GET]

backend_templatemodule_create:
    path:  /create
    defaults:
        _controller: BackendBundle:TemplateModule:create
    methods: [POST]

backend_templatemodule_edit:
    path:  /edit
    defaults:
        _controller: BackendBundle:TemplateModule:edit
    requirements:
    methods: [POST, PUT]

backend_templatemodule_delete:
    path:  /delete
    defaults:
        _controller: BackendBundle:TemplateModule:delete
    requirements:
    methods: [DELETE]

backend_templatemodule_view:
    path:  /view
    defaults:
        _controller: BackendBundle:TemplateModule:view
    requirements:
    methods: [POST]

backend_templatemodule_info:
    path:  /info
    defaults:
        _controller: BackendBundle:TemplateModule:info
    requirements:
    methods: [POST]
