frontend_security_login:
    path: /login
    defaults: { _controller: FrontendBundle:Security:login }
    methods: [GET, POST]

frontend_security_logout:
    path: /logout
    defaults: { _controller: FrontendBundle:Security:logout }
    methods: [GET, POST]

frontend_security_register:
    path: /register
    defaults: { _controller: FrontendBundle:Security:register }
    methods: [GET, POST]



#main_security_login_check:
#    path: /login_check
#
#main_security_logout:
#    path: /logout
