_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /core
#    type:     annotation

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /backend
    #type:     annotation

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
