# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
#    parameter_name: value

imports:
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: "@FrontendBundle/Resources/config/services.yml" }


#services:
#  twig.extension.intl:
#      class: Twig_Extensions_Extension_Intl
#      tags:
#          - { name: twig.extension }


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
