<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * AclObjectIdentitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclObjectIdentitiesRepository extends EntityRepository
{

    public function findAll()
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("
            SELECT t1.id id_object_identities, t1.*, t2.id id_classes, t2.*
                FROM acl_object_identities AS t1
                INNER JOIN acl_classes AS t2
            WHERE
                t1.class_id = t2.id
            
        ");
//        $statement->bindValue('id', 123);
        $statement->execute();
        return $statement->fetchAll();

    }


}
