<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use CoreBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * ChatBotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatBotRepository extends EntityRepository
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['id' => 'DESC'], $limit, $offset);
    }

    public function findAllByParent($parent)
    {

    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT chatbot
            FROM CoreBundle:ChatBot chatbot
            WHERE
            chatbot.id = :id AND
            chatbot.isActive = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function search($lastUserMessage)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT chatbot
            FROM CoreBundle:ChatBot chatbot
            WHERE
            chatbot.name LIKE :lastUserMessage AND
            chatbot.isActive = :active
            ORDER BY chatbot.id DESC
            ";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);
        $query->setParameter('active', 1);
        $query->setParameter('lastUserMessage', "%" . trim($lastUserMessage) . "%");

        return $query->getOneOrNullResult();
    }

}
