<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC'], $limit, $offset);
    }

    public function findAllByCourseId($cursoId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT course, exam
            FROM CoreBundle:Course course
            LEFT JOIN course.exam exam
            WHERE
            course.idIncrement = :curso_id AND
            course.isActive = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('curso_id', $cursoId);

        return $query->getResult();
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT exam
            FROM CoreBundle:Exam exam
            WHERE
            exam.idIncrement = :id AND
            exam.isActive = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function findAllBoxOneToMany($limit = null)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT exam
            FROM CoreBundle:Exam exam
            WHERE
            exam.isActive = :active
            ORDER BY exam.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);

        return $query->getResult();
    }

    public function search($q, $maxResults = null, $firstResult = null)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT exam
            FROM CoreBundle:Exam exam
            WHERE
            (exam.idIncrement LIKE :q OR exam.name LIKE :q) AND
            exam.isActive = :active 
            ORDER BY exam.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('q', '%' . $q . '%');

        if($maxResults){
            $query->setMaxResults($maxResults);
        }

        if($firstResult){
            $query->setFirstResult($firstResult);
        }

        return $query->getResult();
    }

}
