<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC']);
    }

    public function findOneByUniqueId($uniqueId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT file
            FROM CoreBundle:Files file
            WHERE
            file.uniqueId = :id AND
            file.isActive = :isActive
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('isActive', 1);
        $query->setParameter('id', $uniqueId);

        return $query->getOneOrNullResult();
    }

    public function findOneByIdFile($idFile)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT file
            FROM CoreBundle:Files file
            WHERE
            file.idFile = :idFile
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('idFile', $idFile);

        return $query->getOneOrNullResult();
    }
}
