<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FileMimeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.FileMimeTypeRepository
 */
class FileMimeTypeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC']);
    }

    public function findOneByName($name)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT mimeType
            FROM CoreBundle:FileMimeType mimeType
            WHERE
            mimeType.name = :name AND
            mimeType.isActive = :isActive
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('isActive', 1);
        $query->setParameter('name', $name);

        return $query->getOneOrNullResult();
    }
}
