<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GcmRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('status' => true), array('idIncrement' => 'DESC')); //'status' => 1
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT gcm
            FROM CoreBundle:Gcm gcm
            WHERE
            gcm.idIncrement = :id
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }


}
