<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QrRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('status' => 1), array('idIncrement' => 'DESC'));
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT qr
            FROM CoreBundle:Qr qr
            WHERE
            qr.idIncrement = :id AND
            qr.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }
}
