<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('status' => 1), array('idIncrement' => 'DESC'));
    }

    public function findOneById($id)
    {

        $em = $this->getEntityManager();
        $dql = "
            SELECT session
            FROM CoreBundle:Session session
            WHERE
            session.idIncrement = :id AND
            session.status = :status
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('status', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }
}
