<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CoreBundle\Services\Crud\BuildInterface\CrudInterface;
use CoreBundle\Services\ListHasTree\BuildInterface\ListHasTreeInterface;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository implements CrudInterface, ListHasTreeInterface
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC'], $limit, $offset);
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT template
            FROM CoreBundle:Template template
            WHERE
            template.idIncrement = :id AND
            template.active = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function findActiveTemplateById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT template
            FROM CoreBundle:Template template
            WHERE
            template.idIncrement = :id AND
            template.isActive = :active AND
            template.isActiveTemplate = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    /*
    public function findActiveTemplate()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT template
            FROM CoreBundle:Template template
            WHERE
            template.isActive = :active AND
            template.isActiveTemplate = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);

        return $query->getOneOrNullResult();
    }
    */

    public function search($q, $maxResults = null, $firstResult = null)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT template
            FROM CoreBundle:Template template
            WHERE
            (template.idIncrement LIKE :q OR template.name LIKE :q) AND
            template.isActive = :active
            ORDER BY template.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('q', '%' . $q . '%');

        if($maxResults){
            $query->setMaxResults($maxResults);
        }

        if($firstResult){
            $query->setFirstResult($firstResult);
        }

        return $query->getResult();
    }

    public function findAllObjects()
    {
        return $this->createQueryBuilder('a')
            ->where('a.isActive = :active')
            ->orderBy('a.idIncrement', 'DESC')
            ->setParameter('active', true)
            ;
    }

    public function findBoxleftHasBoxright($boxLeftId)
    {
        // TODO: Implement findBoxleftHasBoxright() method.
    }

    public function findBoxleftHasBoxrightCheckIsActive($template, $page)
    {
        // TODO: Implement findBoxleftHasBoxrightCheckIsActive() method.
    }

    public function findBoxleftHasBoxrightCheckIsNotActive($template, $page)
    {
        // TODO: Implement findBoxleftHasBoxrightCheckIsNotActive() method.
    }

    public function findBoxleftHasBoxrightParent($boxLeftId)
    {
        // TODO: Implement findBoxleftHasBoxrightParent() method.
    }

    public function findAllByParent($parent)
    {
        // TODO: Implement findAllByParent() method.
    }
}
