<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * TemplateEPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateEPostRepository extends EntityRepository
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC'], $limit, $offset);
    }

    public function findAllByTemplateHasModule($templateHasModuleId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT post
            FROM CoreBundle:TemplateEPost post
            INNER JOIN post.templateHasModule templateHasModule
            WHERE
            templateHasModule.idIncrement = :id AND
            post.isActive = :active
            ORDER BY post.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $templateHasModuleId);

        return $query->getResult();
    }

}
