#    default.example:
#        class: BackendBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
#    frontend.form.userregistertype:
#        class: FrontendBundle\Form\UserRegisterType
#        arguments: ['@doctrine.orm.entity_manager']
#        tags:
#            - { name: form.type, alias: frontend.form.userregistertype }
